"""Generate a `configs/set_piece_takers.yaml` season block from the FPL API.

The FPL bootstrap-static payload carries authoritative set-piece order fields
per element (`penalties_order`, `direct_freekicks_order`,
`corners_and_indirect_freekicks_order`), maintained by FPL itself. That is a
better source than hand-curating web_names from community trackers, and it can
be refreshed mid-season when roles change.

Usage (writes YAML to stdout; paste into configs/set_piece_takers.yaml):

    uv run python scripts/gen_set_piece_takers.py --season-id 26

By default reads the newest ingested `data/raw/fpl_api/*/bootstrap-static.json`
so it costs no API request; pass --fetch to pull a fresh payload.

Caveat: FPL populates these fields for ~1/4 of elements, and only for clubs it
has decided on — promoted clubs and unsettled roles come through empty. Teams
with no listed taker are omitted from the block, which leaves their players'
`is_corner_taker` / `is_fk_taker` features at 0 (the same state as an absent
season block) rather than asserting a taker we do not know.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

RAW_DIR = Path("data/raw/fpl_api")


def _newest_bootstrap() -> Path:
    paths = sorted(RAW_DIR.glob("*/bootstrap-static.json"))
    if not paths:
        raise FileNotFoundError(
            f"No ingested bootstrap under {RAW_DIR}. Run `gaffe ingest fpl` first, "
            "or pass --fetch."
        )
    return paths[-1]


def _ordered_names(elements: list[dict[str, Any]], field: str) -> list[str]:
    """web_names of elements with a non-null order for `field`, best first."""
    ranked = [(e[field], e["web_name"]) for e in elements if e.get(field) is not None]
    return [name for _order, name in sorted(ranked)]


def build_block(payload: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """{team full name: {penalty, direct_fk, corner}} for teams with any taker."""
    team_name = {t["id"]: t["name"] for t in payload["teams"]}
    by_team: dict[int, list[dict[str, Any]]] = {}
    for element in payload["elements"]:
        by_team.setdefault(element["team"], []).append(element)

    block: dict[str, dict[str, Any]] = {}
    for team_id, elements in by_team.items():
        penalties = _ordered_names(elements, "penalties_order")
        direct_fk = _ordered_names(elements, "direct_freekicks_order")
        corner = _ordered_names(elements, "corners_and_indirect_freekicks_order")
        if not (penalties or direct_fk or corner):
            continue
        info: dict[str, Any] = {}
        if penalties:
            info["penalty"] = penalties[0]
        if direct_fk:
            info["direct_fk"] = direct_fk
        if corner:
            info["corner"] = corner
        block[team_name[team_id]] = info
    return block


def _yaml_list(names: list[str]) -> str:
    return "[" + ", ".join(_yaml_scalar(n) for n in names) + "]"


def _yaml_scalar(value: str) -> str:
    # Quote anything YAML could misread (apostrophes, colons, leading symbols).
    if any(c in value for c in ":'\"#{}[],&*?|<>=!%@`") or value != value.strip():
        return "'" + value.replace("'", "''") + "'"
    return value


def render(season_id: int, block: dict[str, dict[str, Any]]) -> str:
    lines = [f"{season_id}:"]
    for team in sorted(block):
        info = block[team]
        lines.append(f"  {_yaml_scalar(team)}:")
        if "penalty" in info:
            lines.append(f"    penalty: {_yaml_scalar(info['penalty'])}")
        if "direct_fk" in info:
            lines.append(f"    direct_fk: {_yaml_list(info['direct_fk'])}")
        if "corner" in info:
            lines.append(f"    corner: {_yaml_list(info['corner'])}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--season-id", type=int, required=True, help="e.g. 26 for 2026-27")
    parser.add_argument(
        "--fetch", action="store_true", help="Fetch a fresh bootstrap instead of reading raw/"
    )
    args = parser.parse_args()

    if args.fetch:
        from fpl_bot.ingest import fpl_api

        path = fpl_api.fetch_raw_fpl_api("bootstrap-static")
    else:
        path = _newest_bootstrap()

    payload = json.loads(path.read_text())
    block = build_block(payload)
    print(f"# Generated by scripts/gen_set_piece_takers.py from {path}", end="\n")
    print(f"# {len(block)} of {len(payload['teams'])} teams have FPL-listed takers.")
    print(render(args.season_id, block), end="")


if __name__ == "__main__":
    main()
